'use client';
import {useState} from 'react';

const API=process.env.NEXT_PUBLIC_API_BASE||'http://localhost:8000/api/v1';
const segments=[['OTHER','General'],['FAMILY_OFFICE','Family Office'],['ASSET_MANAGER','Asset Manager'],['PENSION_FUND','Pension Fund'],['INSURER','Insurer'],['BANK','Bank'],['CORPORATION','Corporation'],['GOVERNMENT','Government'],['FAMILY_BUSINESS','Family Business'],['SME','SME'],['COMMUNITY','Community']];
export default function AdaptiveClientIntelligence(){
 const [token,setToken]=useState(''); const [segment,setSegment]=useState('OTHER'); const [session,setSession]=useState(null); const [q,setQ]=useState(null); const [other,setOther]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const headers=()=>({'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})});
 async function start(){setBusy(true);setMessage(''); try{const r=await fetch(`${API}/questions/sessions`,{method:'POST',headers:headers(),body:JSON.stringify({segment})}); const d=await r.json(); if(!r.ok)throw new Error(d.detail||'Unable to start'); setSession(d.session_id);setQ(d.question);}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function answer(mode,selected_option=null){setBusy(true);setMessage(''); try{const body={mode,selected_option,free_text:mode==='OTHER'||mode==='FREE_TEXT'?other:null}; const r=await fetch(`${API}/questions/sessions/${session}/answer`,{method:'POST',headers:headers(),body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Answer failed');setOther('');setQ(d.next_question);if(d.completed)setMessage('تم إكمال جلسة الاستخلاص الأولية.');}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="card" id="client-intelligence"><h2>🧠 Client Intelligence · Adaptive Questions</h2><p>أسئلة قصيرة، اختيارات واضحة، وإجابة حرة عند الحاجة. الإجابات الجديدة تتحول إلى إشارات يمكن استخدامها لتطوير الأسئلة اللاحقة.</p>
 {!session?<><label>نوع العميل / المؤسسة</label><select value={segment} onChange={e=>setSegment(e.target.value)}>{segments.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><label>Submitter token</label><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Bearer token"/><button disabled={busy} onClick={start}>ابدأ الحوار الذكي</button></>:<div><div className="badge">Session: {String(session).slice(0,8)}</div>{q&&<><h3>{q.text}</h3><div className="grid">{q.options.map(o=><button key={o} disabled={busy} onClick={()=>answer('CHOICE',o)}>{o}</button>)}</div><hr/><label>لم تجد إجابتك؟</label><textarea value={other} onChange={e=>setOther(e.target.value)} placeholder="اكتب إجابتك بطريقتك..."/><button disabled={busy||!other.trim()} onClick={()=>answer('OTHER')}>إرسال إجابة أخرى</button></>}{message&&<p>{message}</p>}</div>}</section>
}
