'use client';
import {useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1';
const token=()=>typeof window!=='undefined'?localStorage.getItem('cin_api_token')||'':'';
const authHeaders=()=>token()?{Authorization:`Bearer ${token()}`}:{ };
const DIMENSIONS=['authority','directness','recency','validation','consistency','independence','completeness'];
const makeAssessment=(e)=>({evidence_id:e.id,...Object.fromEntries(DIMENSIONS.map(k=>[k,.5])),independence_key:'',confirm_derived_independence:false,derived_independence_key:e.derived_independence_key});
export default function ReviewQueue(){
 const [rows,setRows]=useState([]),[assessments,setAssessments]=useState({}),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const load=()=>fetch(`${API}/assertions/pending`,{headers:authHeaders()}).then(r=>r.json()).then(data=>{setRows(data);setAssessments(prev=>Object.fromEntries(data.map(row=>[row.id,prev[row.id]||row.evidence.map(makeAssessment)])));}).catch(()=>setMsg('تعذر تحميل قائمة المراجعة'));
 useEffect(load,[]);
 const update=(assertionId,index,key,value)=>setAssessments(prev=>({...prev,[assertionId]:prev[assertionId].map((a,i)=>i===index?{...a,[key]:key==='independence_key'?value:Number(value)}:a)}));
 const review=async(id,decision)=>{setBusy(true);setMsg('');try{const r=await fetch(`${API}/assertions/${id}/review`,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({decision,note:'مراجعة بشرية عبر Review Queue',contradiction_score:0,evidence_assessments:assessments[id]||[]})});if(!r.ok)throw new Error((await r.json()).detail||'فشل القرار');await load();setMsg(decision==='VERIFY'?'تم اعتماد الحقيقة وإرسالها إلى الـ Graph.':'تم تسجيل نتيجة المراجعة.')}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 return <section className="card"><h2>مراجعة الأدلة</h2><p>يجب على المراجع تقييم كل دليل. يمكنه أيضاً تحديد مفتاح استقلالية المصدر؛ وإذا تركه فارغاً يستخدم الخادم المفتاح المشتق من مصدر الدليل.</p>{rows.length===0?<p>لا توجد ادعاءات بانتظار المراجعة.</p>:rows.map(r=><article className="review-item" key={r.id}><b>{r.community_name}</b><span>{r.capability_code} — {r.capability_name}</span><small>الثقة الأولية: {r.confidence_level} ({r.confidence_score.toFixed(2)})</small>{(assessments[r.id]||[]).map((a,i)=><div key={a.evidence_id} className="review-assessment"><strong>الدليل {i+1}</strong><label>المفتاح المشتق (غير موثوق بعد)<input value={a.derived_independence_key||''} readOnly/></label><label>مفتاح الاستقلالية المعتمد<input value={a.independence_key} onChange={e=>update(r.id,i,'independence_key',e.target.value)} placeholder="أو اتركه فارغاً"/></label><label><input type="checkbox" checked={!!a.confirm_derived_independence} onChange={e=>update(r.id,i,'confirm_derived_independence',e.target.checked)}/> أؤكد أن المفتاح المشتق يمثل مصدرًا مستقلاً</label><div className="review-dimensions">{DIMENSIONS.map(d=><label key={d}>{d}<input type="number" min="0" max="1" step="0.05" value={a[d]} onChange={e=>update(r.id,i,d,e.target.value)}/></label>)}</div></div>)}<div><button disabled={busy} onClick={()=>review(r.id,'VERIFY')}>اعتماد</button><button disabled={busy} onClick={()=>review(r.id,'CONFLICT')}>تعارض</button><button disabled={busy} onClick={()=>review(r.id,'REJECT')}>رفض</button></div></article>)}{msg&&<p className="message">{msg}</p>}</section>}
