'use client';
import {useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1';
const CODES=['C01','C02','C03','C04','C05','C06','C07','C08','C09','C10'];
export default function ScenarioComparison(){
 const [items,setItems]=useState([]); useEffect(()=>{fetch(`${API}/scenarios`).then(r=>r.json()).then(d=>setItems(d.items||[])).catch(()=>{});},[]);
 const [selected,setSelected]=useState([]); const [factor,setFactor]=useState({}); const [result,setResult]=useState(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 function toggle(id){setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id].slice(0,10));}
 async function compare(){if(selected.length<2){setError('اختر سيناريوهين على الأقل.');return;} setBusy(true);setError(''); try{const assumptions={}; selected.forEach(id=>assumptions[id]={...factor}); const r=await fetch(`${API}/scenarios/compare`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario_ids:selected,assumptions_by_scenario:assumptions})}); const d=await r.json(); if(!r.ok)throw Error(d.detail||'COMPARE_FAILED');setResult(d.items||[]);}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="card"><h2>مقارنة ومحاكاة السيناريوهات</h2><p>اختبر حساسية المسارات لافتراضات توفر القدرات. هذه ليست تنبؤات أو أحكامًا على المجتمعات.</p><div>{items.map(s=><label key={s.id} style={{display:'block',margin:'6px 0'}}><input type="checkbox" checked={selected.includes(s.id)} onChange={()=>toggle(s.id)}/> {s.goal} — {s.steps?.map(x=>x.code).join(' → ')}</label>)}</div><details><summary>تعديل افتراض توفر القدرات</summary><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:8,marginTop:10}}>{CODES.map(c=><label key={c}>{c}<input type="number" min="0" max="1" step="0.1" value={factor[c]??1} onChange={e=>setFactor({...factor,[c]:Number(e.target.value)})}/></label>)}</div></details><button onClick={compare} disabled={busy}>{busy?'جارٍ المحاكاة…':'قارن السيناريوهات'}</button>{error&&<p className="error">{error}</p>}{result&&<div>{result.map((x,i)=><div className="scenario" key={x.scenario_id}><h3>{i+1}. {x.goal}</h3><strong>Support Score: {x.support_score}</strong><ol>{x.steps.map(st=><li key={st.order}>{st.code} — {st.community} · base {st.base_confidence} × availability {st.availability_factor} = {st.effective_support}</li>)}</ol></div>)}</div>}</section>
}
