'use client';
import {useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1';
const token=()=>typeof window!=='undefined'?localStorage.getItem('cin_api_token')||'':'';
const authHeaders=()=>token()?{Authorization:`Bearer ${token()}`}:{ };
export default function SubmissionForm({onSubmitted}){
 const [caps,setCaps]=useState([]),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[msg,setMsg]=useState('');
 const [form,setForm]=useState({community:{name:'',country_code:'EG',location:'',population:'',description:''},capability_type_id:'',scope:'',scale:'',quantity:'',unit:'',measurement_period:'',maturity_level:'EMERGING',evidence:[{title:'',evidence_type:'document',content_text:'',content_url:'',sha256:'',mime_type:'',size_bytes:null}]});
 useEffect(()=>{fetch(`${API}/capabilities`).then(r=>r.json()).then(setCaps).catch(()=>setMsg('تعذر تحميل مجالات القدرة'))},[]);
 const set=(k,v)=>setForm(f=>({...f,[k]:v})); const setEv=(k,v)=>setForm(f=>({...f,evidence:[{...f.evidence[0],[k]:v}]}));
 const upload=async(file)=>{if(!file)return;setUploading(true);setMsg('جارٍ رفع الدليل…');try{const fd=new FormData();fd.append('file',file);const r=await fetch(`${API}/evidence/upload`,{method:'POST',headers:authHeaders(),body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail||'فشل رفع الملف');setEv('content_url',d.content_url);setEv('sha256',d.sha256);setEv('mime_type',d.mime_type);setEv('size_bytes',d.size_bytes);setEv('original_filename',d.filename);setMsg('تم رفع الدليل. أكمل بياناته ثم أرسل الادعاء.')}catch(e){setMsg(e.message)}finally{setUploading(false)}};
 const submit=async e=>{e.preventDefault();setBusy(true);setMsg('جارٍ الحفظ…');try{const payload={...form,community:{...form.community,population:form.community.population?Number(form.community.population):null},quantity:form.quantity?Number(form.quantity):null};const r=await fetch(`${API}/assertions/submit`,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.detail||'فشل الإرسال');setMsg(`تم الإرسال للمراجعة البشرية. الثقة الأولية: ${d.confidence_level} (${d.confidence_score.toFixed(2)})`);onSubmitted?.()}catch(err){setMsg(err.message)}finally{setBusy(false)}};
 return <form className="card" onSubmit={submit} dir="rtl"><h2>إضافة قدرة حضارية</h2><label>اسم المجتمع<input required value={form.community.name} onChange={e=>set('community',{...form.community,name:e.target.value})}/></label><label>الدولة<input value={form.community.country_code} onChange={e=>set('community',{...form.community,country_code:e.target.value})}/></label><label>الموقع<input value={form.community.location} onChange={e=>set('community',{...form.community,location:e.target.value})}/></label><label>عدد السكان<input type="number" value={form.community.population} onChange={e=>set('community',{...form.community,population:e.target.value})}/></label><label>نوع القدرة<select required value={form.capability_type_id} onChange={e=>set('capability_type_id',e.target.value)}><option value="">اختر C01–C10</option>{caps.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></label><label>النطاق<input value={form.scope} onChange={e=>set('scope',e.target.value)}/></label><label>الحجم / الكمية<input value={form.quantity} onChange={e=>set('quantity',e.target.value)}/></label><label>الوحدة<input value={form.unit} onChange={e=>set('unit',e.target.value)}/></label><label>مستوى النضج<select value={form.maturity_level} onChange={e=>set('maturity_level',e.target.value)}><option>EMERGING</option><option>DEVELOPING</option><option>ESTABLISHED</option><option>ADVANCED</option><option>SPECIALIZED</option></select></label><h3>الدليل</h3><label>عنوان الدليل<input required value={form.evidence[0].title} onChange={e=>setEv('title',e.target.value)}/></label><label>رفع ملف<input type="file" accept=".pdf,.png,.jpg,.jpeg,.txt,.csv" onChange={e=>upload(e.target.files?.[0])} disabled={uploading}/></label>{form.evidence[0].original_filename&&<small>الملف: {form.evidence[0].original_filename} · SHA-256: {form.evidence[0].sha256}</small>}<label>رابط الدليل<input value={form.evidence[0].content_url} onChange={e=>setEv('content_url',e.target.value)}/></label><label>وصف/محتوى الدليل<textarea required value={form.evidence[0].content_text} onChange={e=>setEv('content_text',e.target.value)}/></label><button disabled={busy||uploading}>{busy?'جارٍ الحفظ…':'إرسال للمراجعة'}</button>{msg&&<p className="message">{msg}</p>}</form>
}
